using Testimonial
using Test
using Dates

include("helpers.jl")

include("test_types.jl")
include("test_persistence.jl")
include("test_protocol.jl")
include("test_astparser.jl")
include("test_gitdiff.jl")
include("test_runner.jl")
include("test_driver.jl")
include("test_command.jl")
include("test_runner_types.jl")
include("test_indexbuilder.jl")
include("test_mockrunner.jl")
include("test_cov_sidecar.jl")
include("test_timeout.jl")
include("test_subprocess_record.jl")
include("test_changed_detection.jl")
include("test_query.jl")
include("test_record_all.jl")
include("test_build_index_integration.jl")
include("test_cli.jl")
include("test_always_run.jl")
include("test_environment_fingerprint.jl")
include("test_must_run_config.jl")
include("test_must_run_query.jl")
include("test_scoped_fallback.jl")
include("test_must_run_priority.jl")
include("test_seeded_fault.jl")
include("test_seeded_fault_verify.jl")
include("test_must_run_integration.jl")